server:
  port: ${PORT:8080}

spring:
  application:
    name: backend
  main:
    banner-mode: "off"
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://${DB_HOST:mainline.proxy.rlwy.net}:${DB_PORT:33030}/${DB_NAME:railway}
    username: ${DB_USER:postgres}
    password: ${2012}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
