spring:
  application:
    name: ${APP_NAME:Afripay Backend}
  main:
    banner-mode: "off"
  profiles:
    active: ${APP_ENV:dev}

server:
  port: ${PORT:8000}

jwt:
  secret: ${JWT_SECRET:my_super_secure_token_key}
  expiration: ${JWT_EXPIRATION:86400000}

afripay:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
